# Builds SEAPATH and uploads SBOM artifacts.
# This is a reusable workflow that cannot be launched directly.
---
name: Build (internal)

on:
  workflow_call:
    inputs:
      origin_repo:
        type: string
        required: true
        description: Repository that triggered this workflow dispatch.
      origin_ref:
        type: string
        required: true
        description: >-
          Git ref of the commit that triggered the build on the origin
          repository.

jobs:
  build:
    runs-on: ["self-hosted", "linux", "cqfd", "repo"]
    strategy:
      fail-fast: true # TODO eventually set to false
      max-parallel: 1
      matrix:
        cqfd_flavor: ${{ fromJSON(vars.CQFD_FLAVORS) }}
    env:
      REPO_MANIFEST_URL: https://github.com/${{ vars.REPO_MANIFEST_REPOSITORY }}
      REPO_MANIFEST_REF: ${{ case(inputs.origin_repo == vars.REPO_MANIFEST_REPOSITORY, inputs.origin_ref, 'HEAD') }}
      REPO_MANIFEST_NAME: default.xml
      WORKSPACE: workspace-bitbake
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    steps:
      - name: Create workspace
        working-directory: ${{ github.workspace }}
        run: mkdir -p ${{ env.WORKSPACE }}

      - name: Init repo
        run: |
          repo init -u "$REPO_MANIFEST_URL" -b "$REPO_MANIFEST_REF" -m "$REPO_MANIFEST_NAME"
          repo sync

      - name: Checkout specific ref
        if: inputs.origin_repo != vars.REPO_MANIFEST_REPOSITORY
        run: |
          # TODO

      - name: Init build system
        run: |
          cqfd init
          touch "keys/ansible_public_ssh_key.pub"
          cp seapath.conf.sample seapath.conf

      - name: Cleanup old builds
        if: vars.CLEAN_BUILD_DIR
        run: |
          rm -rf build

      - name: Build ${{ matrix.cqfd_flavor }}
        run: |
          # Since we are in a non-interactive bash, the bashrc file is not
          # read and CQFD environment variables are not used, especially the
          # Yocto cache -related ones... Thus we source the bashrc file.
          source /etc/bash.bashrc
          cqfd -b ${{ matrix.cqfd_flavor }}

      - name: Upload SBOM files
        uses: actions/upload-artifact@v6
        with:
          name: sbom-${{ matrix.cqfd_flavor }}
          path: |
            ${{ env.WORKSPACE }}/build/tmp/deploy/images/**/*.rootfs.json
            ${{ env.WORKSPACE }}/build/tmp/deploy/images/**/*.rootfs.spdx.tar.zst
          if-no-files-found: warn

      - name: Clean build directory
        if: always() && vars.CLEAN_BUILD_DIR
        run: |
          rm -rf build
