name: CI

on:
  # TODO: make the workflow triggerable by all SEAPATH-related repositories
  # using a "repository_dispatch" trigger:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#repository_dispatch
  workflow_dispatch:

jobs:
  build:
    runs-on: ["self-hosted", "linux", "cqfd", "repo"]
    strategy:
      fail-fast: true # TODO eventually set to false
      max-parallel: 1
      matrix:
        cqfd_flavor: ["host_efi", "guest_efi", "observer_efi", "host_standalone_efi"]
    env:
      REPO_MANIFEST_REPOSITORY: https://github.com/seapath/repo-manifest
      REPO_MANIFEST_REF: HEAD
      REPO_MANIFEST_NAME: default.xml
      WORKSPACE: workspace-bitbake
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    steps:
      - name: Create workspace
        working-directory: ${{ github.workspace }}
        run: mkdir -p ${{ env.WORKSPACE }}

      - name: Init repo
        run: |
          repo init -u "$REPO_MANIFEST_REPOSITORY" -b "$REPO_MANIFEST_REF" -m "$REPO_MANIFEST_NAME"
          repo sync

      # TODO checkout specific ref based on the even that triggered the CI

      - name: Init build system
        run: |
          cqfd init
          touch "keys/ansible_public_ssh_key.pub"
          cp seapath.conf.sample seapath.conf

      - name: Cleanup old builds
        run: |
          rm -rf build

      - name: Build ${{ matrix.cqfd_flavor }}
        run: |
          # Since we are in a non-interactive bash, the bashrc file is not
          # read and CQFD environment variables are not used, especially the
          # Yocto cache -related ones... Thus we source the bashrc file.
          source /etc/bash.bashrc
          cqfd -b ${{ matrix.cqfd_flavor }}

      - name: Upload SBOM files
        uses: actions/upload-artifact@v6
        with:
          name: sbom-${{ matrix.cqfd_flavor }}
          path: |
            ${{ env.WORKSPACE }}/build/tmp/deploy/images/**/*.rootfs.json
            ${{ env.WORKSPACE }}/build/tmp/deploy/images/**/*.rootfs.spdx.tar.zst
          if-no-files-found: warn

      - name: Clean build directory
        if: always()
        run: |
          rm -rf build

  call-cve-check:
    uses: ./.github/workflows/cve-check.yml
    with:
      build-run-id: ${{ github.run_id }}
