name: Build on push

on:
  # This is for yocto-bsp itself.
  push:
    branches:
      - scarthgap
    paths-ignore:
      - .github/**/*
  # The manual dispatch trigger is for other repositories (such as meta-seapath)
  # that must be able to trigger the build pipeline.
  # We don't use repository_dispatch since there would be no way for the caller
  # workflow to wait for completion (https://github.com/peter-evans/repository-dispatch/issues/260).
  workflow_dispatch:
    inputs:
      origin_repo_project:
        type: string
        required: true
        description: >-
          Name of the project that triggered this workflow dispatch.
          It should correspond to a project name in the repo manifest
          or be "repo-manifest" itself.
      origin_sha:
        type: string
        required: true
        description: >-
          Value of the GITHUB_SHA variable for the workflow on the
          origin repository.

run-name: "Push to ${{ inputs.origin_repo_project || vars.REPO_PROJECT }}"

jobs:
  call-build:
    name: Call Build workflow
    uses: ./.github/workflows/_build.yml
    with:
      origin_repo_project: "${{ inputs.origin_repo_project || vars.REPO_PROJECT }}"
      origin_sha: "${{ inputs.origin_sha || github.sha }}"

  call-cve-check:
    name: Call CVE check workflow
    needs: call-build
    uses: ./.github/workflows/_cve-check.yml
    with:
      build-run-id: ${{ github.run_id }}
