name: Build on push

on:
  # This is for yocto-bsp itself.
  push:
    branches:
      - scarthgap
    paths-ignore:
      - .github/**/*
  # The manual dispatch trigger is for other repositories (such as meta-seapath)
  # that must be able to trigger the build pipeline.
  # We don't use repository_dispatch since there would be no way for the caller
  # workflow to wait for completion (https://github.com/peter-evans/repository-dispatch/issues/260).
  workflow_dispatch:
    inputs:
      origin_repo:
        type: string
        required: true
        description: Repository that triggered this workflow dispatch.
      origin_ref:
        type: string
        required: true
        description: >-
          Git ref of the commit that triggered the build on the origin
          repository.

jobs:
  call-build:
    name: Call Build workflow
    uses: ./.github/workflows/_build.yml
    with:
      origin_repo: "${{ case(github.event_name == 'workflow_dispatch', github.event.inputs.origin_repo, github.repository) }}"
      origin_ref: "${{ case(github.event_name == 'workflow_dispatch', github.event.inputs.origin_ref, github.ref) }}"

  call-cve-check:
    name: Call CVE check workflow
    needs: call-build
    uses: ./.github/workflows/_cve-check.yml
    with:
      build-run-id: ${{ github.run_id }}
